name: Deploy to EC2 senisha promotion app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.LS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.LS_PUBLIC_IP }} >> ~/.ssh/known_hosts
        
    - name: Deploy to EC2 Instance
      run: |
        rsync -avz --delete --exclude-from=".rsyncignore" -e "ssh -i ~/.ssh/id_rsa" ./ ${{ secrets.LS_USER }}@${{ secrets.LS_PUBLIC_IP }}:/var/www/senisha-promotion/
        ssh -i ~/.ssh/id_rsa ${{ secrets.LS_USER }}@${{ secrets.LS_PUBLIC_IP }} 'cd /var/www/senisha-promotion/'
      
    - name: Clear SSH
      run: rm ~/.ssh/id_rsa
